## Easy

In [1]:
##1. import numpy
import numpy as np

In [6]:
##2. check numpy version
np.__version__

'1.18.1'

In [7]:
##3. Create a null vector of size 10
v = np.zeros(10)

In [14]:
##4. How to find the memory size of any array

#size of an array
print(v.size)

#size of an item of an array (in bytes)
print(str(v.itemsize) + " Bytes")

#memory size of an array (... bytes)
print(str(v.itemsize * v.size) + " Bytes")

10
8 Bytes
80 Bytes


In [15]:
##5. How to get the documentation of the numpy add function from the command line?

print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [16]:
##6. Create a null vector of size 10 but the fifth value which is 1.

#null vector of size 10
v = np.zeros(10)

#change the value of 4th index to 1
v[4] = 1

print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [20]:
##7. Create a vector with values ranging from 10 to 49

vector2 = np.arange(10,50)
vector2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [21]:
##8. Reverse a vector (first element becomes last)
vector3 = vector2[::-1]
vector3

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [26]:
##9. Create a 3x3 matrix with values ranging from 0 to 8

mat_1 = np.arange(0,9).reshape(3,3)
mat_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
##10. Find indices of non-zero elements from [1,2,0,0,4,0]
vector4 = [1,2,0,0,4,0]
print(np.nonzero(vector4))

(array([0, 1, 4], dtype=int64),)


In [30]:
##11. Create a 3x3 identity matrix
mat2 = np.identity(3)
mat2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
##12. Create a 3x3x3 array with random values
mat3 = np.random.random((3,3,3)) # gives float output of interval 0-1
mat3

array([[[0.12868255, 0.60635813, 0.47722889],
        [0.31826651, 0.31892532, 0.04325009],
        [0.55849796, 0.76754974, 0.43233281]],

       [[0.81284336, 0.99849247, 0.20317239],
        [0.93110171, 0.48241872, 0.16891368],
        [0.04503189, 0.33516063, 0.13973688]],

       [[0.51159717, 0.36570006, 0.07220198],
        [0.78247435, 0.3976016 , 0.44595421],
        [0.73052962, 0.63055174, 0.37342776]]])

In [42]:
##13. Create a 10x10 array with random values and find the minimum and maximum values
mat3 = np.random.random((10,10))
mat3_min, mat3_max = mat3.min(), mat3.max()
print(mat3)
print(mat3_min)
print(mat3_max)

[[0.24191782 0.18599662 0.70340442 0.81193457 0.94180579 0.54976137
  0.32293404 0.10684974 0.02004083 0.85505771]
 [0.16625414 0.71500998 0.02641436 0.88119582 0.44418803 0.16136267
  0.47499762 0.71864208 0.76958252 0.01394951]
 [0.18908531 0.11609424 0.19448106 0.97645634 0.93501449 0.23645081
  0.88657619 0.14978645 0.67058179 0.12454554]
 [0.29708551 0.58457497 0.70461164 0.0391311  0.80152966 0.2409321
  0.60045524 0.19323653 0.34243682 0.96644213]
 [0.4697065  0.55311402 0.76633003 0.22528713 0.14813966 0.55910714
  0.66391778 0.47039803 0.08309723 0.43951315]
 [0.04670126 0.50489375 0.47765259 0.56140086 0.56319935 0.87883719
  0.78340544 0.64820164 0.3325846  0.96676956]
 [0.55242943 0.50380347 0.17578983 0.42132333 0.71254572 0.52968182
  0.78461744 0.51592343 0.47655511 0.48244235]
 [0.40383648 0.75286888 0.40976169 0.94740676 0.34273246 0.46702378
  0.30988516 0.32811432 0.88965998 0.79670125]
 [0.72437315 0.46159941 0.1102347  0.99800631 0.24934287 0.81582221
  0.37995591 

In [44]:
##14. Create a random vector of size 30 and find the mean value
vector5 = np.random.random((30))
print(vector5)
print(vector5.mean())

[0.26489502 0.10223834 0.76340871 0.14756509 0.37657475 0.38844834
 0.19516005 0.1392775  0.81400021 0.90190929 0.62309265 0.68558023
 0.39274114 0.99272901 0.88500366 0.41608771 0.31882093 0.59928171
 0.97851824 0.27034472 0.54499802 0.22171659 0.79619162 0.0511377
 0.68203685 0.80451769 0.08932113 0.06992835 0.20649119 0.49757353]
0.4739863322738293


In [52]:
##15. Create a 2d array with 1 on the border and 0 inside
mat4 = np.ones((6,6))
mat4[1:-1,1:-1] = 0
mat4

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [53]:
##16. How to add a border (filled with 0's) around an existing array?
mat4 = np.pad(mat4, pad_width = 1, mode = 'constant', constant_values = 0)
mat4

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
##17. What is the result of the following expression?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [69]:
##18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal @@@
mat5 = np.diag(1+np.arange(4),k=-1)
mat5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [82]:
##19. Create a 8x8 matrix and fill it with a checkerboard pattern 
mat6 = np.ones((8,8))
mat6[0::2, ::2] = 0
mat6[1::2, 1::2] = 0
mat6

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [83]:
##20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? @@@
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


In [5]:
##21. Create a checkerboard 8x8 matrix using the tile function
mat7 = [[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0]]
repeatation = (4,1)
mat7 = np.tile(mat7, repeatation)
mat7

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [6]:
##22. Normalize a 5x5 random matrix
mat8 = np.random.random((5,5))
mat8 = (mat8 - np.mean (mat8)) / (np.std (mat8))
mat8

array([[ 0.91456927,  0.05141491, -0.79745126,  1.33063733,  0.09278928],
       [-1.25425771, -0.38942689,  0.36187461,  1.61660331,  0.18663784],
       [ 1.23759982, -0.27346245,  1.55861803,  0.47916684, -0.18667811],
       [-1.57580562,  0.15307018,  1.42642111, -0.93436223, -1.08225003],
       [ 0.46418043, -1.59073741,  0.45966463, -0.46476942, -1.78404646]])

In [11]:
##23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)  @@@
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [12]:
##24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
mat9 = np.dot(np.ones((5,3)), np.zeros((3,2)))
mat9

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
##25. Given a 1D array, negate all elements which are between 3 and 8, in place @@@
mat10 = np.arange(15)
mat10[(3<mat10) & (mat10<8)] *= -1
mat10

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
##26. What is the output of the following script?
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [12]:
range(5),-1

(range(0, 5), -1)

In [19]:
##27. Consider an integer vector Z, which of these expressions are legal?
list2 = [[1],
        [2],
        [3]]
Z = np.array(list2)
                    #Z**Z
                    #2 << Z >> 2
                    #Z <- Z
                    #1j*Z
                    #Z/1/1
                    #Z<Z>Z

In [20]:
Z**Z # ** means power

array([[ 1],
       [ 4],
       [27]], dtype=int32)

In [21]:
2 << Z >> 2 # @@@

array([[1],
       [2],
       [4]], dtype=int32)

In [22]:
Z < -Z

array([[False],
       [False],
       [False]])

In [23]:
1j * Z

array([[0.+1.j],
       [0.+2.j],
       [0.+3.j]])

In [27]:
Z/1/1

array([[1.],
       [2.],
       [3.]])

In [28]:
Z.dtype

dtype('int32')

In [30]:
Z<Z>Z ## doesnt work.. (invalid)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [31]:
##28. What are the result of the following expressions?
            #np.array(0) / np.array(0)
            #np.array(0) // np.array(0)
            #np.array([np.nan]).astype(int).astype(float)

In [32]:
np.array(0)

array(0)

In [33]:
np.array(0)/np.array(0) # 0 / 0   ....

C:\Users\Abirk\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [34]:
np.array(0) // np.array(0)

C:\Users\Abirk\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [36]:
np.array([np.nan]).astype(int).astype(float)  # how?  

array([-2.14748365e+09])

In [42]:
np.array([np.nan]).astype(int)

array([-2147483648])