In [17]:
##1. import numpy
import numpy as np

In [6]:
##2. check numpy version
np.__version__

'1.18.1'

In [7]:
##3. Create a null vector of size 10
v = np.zeros(10)

In [14]:
##4. How to find the memory size of any array

#size of an array
print(v.size)

#size of an item of an array (in bytes)
print(str(v.itemsize) + " Bytes")

#memory size of an array (... bytes)
print(str(v.itemsize * v.size) + " Bytes")

10
8 Bytes
80 Bytes


In [15]:
##5. How to get the documentation of the numpy add function from the command line?

print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [16]:
##6. Create a null vector of size 10 but the fifth value which is 1

#null vector of size 10
v = np.zeros(10)

#change the value of 4th index to 1
v[4] = 1

print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [20]:
##7. Create a vector with values ranging from 10 to 49

vector2 = np.arange(10,50)
vector2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [21]:
##8. Reverse a vector (first element becomes last)
vector3 = vector2[::-1]
vector3

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [26]:
##9. Create a 3x3 matrix with values ranging from 0 to 8

mat_1 = np.arange(0,9).reshape(3,3)
mat_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
##10. Find indices of non-zero elements from [1,2,0,0,4,0]
vector4 = [1,2,0,0,4,0]
print(np.nonzero(vector4))

(array([0, 1, 4], dtype=int64),)


In [30]:
##11. Create a 3x3 identity matrix
mat2 = np.identity(3)
mat2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
##12. Create a 3x3x3 array with random values
mat3 = np.random.random((3,3,3)) # giver float output of interval 0-1
mat3

array([[[0.12868255, 0.60635813, 0.47722889],
        [0.31826651, 0.31892532, 0.04325009],
        [0.55849796, 0.76754974, 0.43233281]],

       [[0.81284336, 0.99849247, 0.20317239],
        [0.93110171, 0.48241872, 0.16891368],
        [0.04503189, 0.33516063, 0.13973688]],

       [[0.51159717, 0.36570006, 0.07220198],
        [0.78247435, 0.3976016 , 0.44595421],
        [0.73052962, 0.63055174, 0.37342776]]])